org: roxx3r
app: merlin
service: merlin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    ETHERSCAN_KEY: ${self:custom.secrets.etherscan.api_key}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
        - dynamodb:Query
      Resource:
        - "Fn::GetAtt": [ merlin, Arn ]

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-domain-manager
  - serverless-plugin-include-dependencies
  - serverless-api-gateway-caching

custom:
  secrets: ${file(secrets.yml)}
  customDomain:
    domainName: "wenmerl.in"
    certificateName: "wenmerl.in"
    createRoute53Record: true
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 150

functions:
  site:
    handler: src/lambda-site.handler
    timeout: 12
    events:
      - http:
          path: /
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.querystring.wallet

  fees:
    handler: src/lambda-fees.handler
    timeout: 120
    events:
      - schedule: rate(5 minutes)

resources:
  Resources:
    merlin:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: merlin
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: N
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
